server:
  display-name: union
  context-path: /
  port: 8081

# logback配置
logging:
  config: classpath:logback-spring.xml

spring:
  # druid配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://113.106.202.51:3306/gt_union_ceshi?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: gt123456
    # 初始化大小、最大、最小
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: false
  # redis配置
  redis:
      host: 113.106.202.51
      port: 6379
      password: gt@123456
      timeout: 0
      database: 2
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  session:
       store-type: redis

# mybatis设置
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.gt.union.entity


######################## 全局配置 ########################


#图片存放路径
res:
  image:
    path: G:\git_workplace\MedicalSys\src\main\resources\static\upload
#访问资源URL
resource:
  url:
    prefix: http://192.168.3.41:9998/upload/
#本项目访问路径
article:
  url:
    prefix: http://192.168.3.41:9998/upload/
socket:
  url: http://192.168.2.12:8080:8881
#企业短信通-密码
sms:
  pwd: sd18923646688
  content:
   url: http://192.168.2.12:8080/common/%s/%s/79B4DE7C/orderconfirm.do
#域名
domain:
  df: duofriend.com
#mq config
mq:
  uri: 192.168.2.12:8080
  user: guest
  password: yf26609632

#队列转换器
exchange:
  gt:
    exchange: message
#队列名称
queueName:
  gt:
    queueName: message

#图片资源ftp ip
static:
  source:
    ftp:
      ip: 120.25.154.127
      port: 21
      user: gt123456
      password: gt1234561
#图片资源ftp用户名

#redis:
redisNamePrefix: "Union:"


redisSession:
  domainName: .yifriend.net
  cookiePath: /
  cookieName: JSESSIONID

#数据请求地址
wxmp:
   url: http://hz1.yifriend.net
   signkey: WXMP2017
   company: "多粉平台"
   #url: http://deeptel.com.cn/
  #url: http://192.168.3.41:83