server:
  display-name: union
  context-path: /
  port: 8082

# logback配置
logging:
  config: classpath:logback-spring.xml

spring:
  # druid配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://113.106.202.51:3306/gt_union_ceshi20170907?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false
    username: root
    password: gt123456
    # 初始化大小、最大、最小
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 5分钟
    timeBetweenEvictionRunsMillis: 300000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000 30秒
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # P白(allow)/黑(deny)名单 (存在共同时，deny优先于allow) : 如果满足deny的话提示:Sorry, you are not permitted to view this page.
    allow: 192.168.3.11
    login-username: admin
    login-password: admin
    reset-enable: false
    url-pattern: /druid/*
    # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
    # 如果spring.datasource.druid.aop-patterns要代理的类没有定义interface请设置spring.aop.proxy-target-class=true
    # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
    aop-patterns: com.gt.union.service.*

  # redis配置
  redis:
      host: 113.106.202.51
      port: 6379
      password: gt@123456
      timeout: 0
      database: 2
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  session:
       store-type: redis

# mybatis设置
mybatis:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.gt.union.*.entity


######################## 全局配置 ########################



#访问资源URL
resource:
  url:
    prefix: http://192.168.3.41:9998/upload/
socket:
  url: http://192.168.2.12:8080:8881
#企业短信通-密码

#域名
domain:
  df: duofriend.com
#mq config
#mq:
#  uri: 192.168.3.59:5672
#  user: admin
#  password: admin
mq:
  uri: 127.0.0.1:5672
  user: admin
  password: admin

#队列转换器
exchange:
  union:
    exchange: union_exchange
#队列名称
queueName:
  union:
    queueName: union_routingKey_phone_message


#redis:
redisNamePrefix: "Union:"


redisSession:
  domainName: .yifriend.net
  cookiePath: /
  cookieName: WXMPJSESSIONID

#数据请求地址
wxmp:
   url: http://hz1.yifriend.net
   signkey: WXMP2017
   company: "多粉平台"

union:
  url: http://union.yifriend.net:7884
  encryptKey: CFCCBD99C12B62E52952EA90A931A01F
  signkey: SR36E9KIYDLIU1VB6WX20HCW494QL97T
wx:
  duofen:
    busId: 33