package com.gt.union.entity.common;

import java.io.Serializable;
import java.util.Date;

public class BusUser implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.id
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.name
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.password
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.email
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.phone
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.gender
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.register_ip
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String registerIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.recent_ip
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String recentIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.ctime
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private Date ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.mtime
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_user.status
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    private String status;
    
    /**
     * 会员级别
     */
    private Integer level;
    
    /**
     * 城市ID
     */
    private Integer city_id;

    
    /**
     * 会员开始时间
     */
    private Date startTime;
    
    
    /**
     * 会员结束时间
     */
    private Date endTime;
    
    /**
     * 会员有效日期
     */
    private Integer days;
    
    private String levelDesc;
    
    /**
     * 会员续费年限
     */
    private Integer years;
    
    
    private Double fansCurrency;
    
    private long flow;
    
    private Integer industryid;
    
    
    private Integer pid;
    
    private Integer smsCount;
    
    private Integer istechnique;
    
    private Integer advert;
    
    private String busmoney_level;
    private String regionids;
    private Integer isagent;
    private Integer agentid;
    
    private String realname;
    
    private Integer login_source;
    
    private Boolean is_binding;
    
    private Date unbundling_time;
    
    
    private String fixed_phone;
    
    private String customer_id;
    
    private String merchant_name;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.id
     *
     * @return the value of bus_user.id
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.id
     *
     * @param id the value for bus_user.id
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.name
     *
     * @return the value of bus_user.name
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.name
     *
     * @param name the value for bus_user.name
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.password
     *
     * @return the value of bus_user.password
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.password
     *
     * @param password the value for bus_user.password
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.email
     *
     * @return the value of bus_user.email
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.email
     *
     * @param email the value for bus_user.email
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.phone
     *
     * @return the value of bus_user.phone
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.phone
     *
     * @param phone the value for bus_user.phone
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.gender
     *
     * @return the value of bus_user.gender
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.gender
     *
     * @param gender the value for bus_user.gender
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.register_ip
     *
     * @return the value of bus_user.register_ip
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getRegisterIp() {
        return registerIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.register_ip
     *
     * @param registerIp the value for bus_user.register_ip
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setRegisterIp(String registerIp) {
        this.registerIp = registerIp == null ? null : registerIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.recent_ip
     *
     * @return the value of bus_user.recent_ip
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getRecentIp() {
        return recentIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.recent_ip
     *
     * @param recentIp the value for bus_user.recent_ip
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setRecentIp(String recentIp) {
        this.recentIp = recentIp == null ? null : recentIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.ctime
     *
     * @return the value of bus_user.ctime
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.ctime
     *
     * @param ctime the value for bus_user.ctime
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.mtime
     *
     * @return the value of bus_user.mtime
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.mtime
     *
     * @param mtime the value for bus_user.mtime
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_user.status
     *
     * @return the value of bus_user.status
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_user.status
     *
     * @param status the value for bus_user.status
     *
     * @mbggenerated Tue Jun 30 11:03:44 CST 2015
     */
    public void setStatus(String status) {
        this.status = status;
    }

	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	public Integer getCity_id() {
		return city_id;
	}

	public void setCity_id(Integer city_id) {
		this.city_id = city_id;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Integer getYears() {
		return years;
	}

	public void setYears(Integer years) {
		this.years = years;
	}

	public Integer getDays() {
		return days;
	}

	public void setDays(Integer days) {
		this.days = days;
	}

	public Double getFansCurrency() {
		return fansCurrency;
	}

	public void setFansCurrency(Double fansCurrency) {
		this.fansCurrency = fansCurrency;
	}

	public Integer getIndustryid() {
		return industryid;
	}

	public void setIndustryid(Integer industryid) {
		this.industryid = industryid;
	}

	public long getFlow() {
		return flow;
	}

	public void setFlow(long flow) {
		this.flow = flow;
	}

	public String getLevelDesc() {
		return levelDesc;
	}

	public void setLevelDesc(String levelDesc) {
		this.levelDesc = levelDesc;
	}

	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public Integer getSmsCount() {
		return smsCount;
	}

	public void setSmsCount(Integer smsCount) {
		this.smsCount = smsCount;
	}

	public Integer getIstechnique() {
		return istechnique;
	}

	public void setIstechnique(Integer istechnique) {
		this.istechnique = istechnique;
	}

	public Integer getAdvert() {
		return advert;
	}

	public void setAdvert(Integer advert) {
		this.advert = advert;
	}

	public String getBusmoney_level() {
		return busmoney_level;
	}

	public void setBusmoney_level(String busmoney_level) {
		this.busmoney_level = busmoney_level;
	}

	public String getRegionids() {
		return regionids;
	}

	public void setRegionids(String regionids) {
		this.regionids = regionids;
	}

	public Integer getIsagent() {
		return isagent;
	}

	public void setIsagent(Integer isagent) {
		this.isagent = isagent;
	}

	public Integer getAgentid() {
		return agentid;
	}

	public void setAgentid(Integer agentid) {
		this.agentid = agentid;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public Integer getLogin_source() {
		return login_source;
	}

	public void setLogin_source(Integer login_source) {
		this.login_source = login_source;
	}

	public Boolean getIs_binding() {
		return is_binding;
	}

	public void setIs_binding(Boolean is_binding) {
		this.is_binding = is_binding;
	}

	public Date getUnbundling_time() {
		return unbundling_time;
	}

	public void setUnbundling_time(Date unbundling_time) {
		this.unbundling_time = unbundling_time;
	}

	public String getFixed_phone() {
		return fixed_phone;
	}

	public void setFixed_phone(String fixed_phone) {
		this.fixed_phone = fixed_phone;
	}

	public String getCustomer_id() {
		return customer_id;
	}

	public void setCustomer_id(String customer_id) {
		this.customer_id = customer_id;
	}

	public String getMerchant_name() {
		return merchant_name;
	}

	public void setMerchant_name(String merchant_name) {
		this.merchant_name = merchant_name;
	}
}