package com.gt.union.webservice.client.common;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-31T15:26:34.898+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebServiceClient(name = "DemoWebServiceImpl", 
                  wsdlLocation = "http://localhost:8080/webservices/demo?wsdl",
                  targetNamespace = "http://common.server.webservice.union.gt.com/") 
public class DemoWebServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://common.server.webservice.union.gt.com/", "DemoWebServiceImpl");
    public final static QName DemoWebServicePort = new QName("http://common.server.webservice.union.gt.com/", "DemoWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/webservices/demo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoWebServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/webservices/demo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoWebServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoWebServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoWebServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DemoWebServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoWebServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoWebServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IDemoWebService
     */
    @WebEndpoint(name = "DemoWebServicePort")
    public IDemoWebService getDemoWebServicePort() {
        return super.getPort(DemoWebServicePort, IDemoWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDemoWebService
     */
    @WebEndpoint(name = "DemoWebServicePort")
    public IDemoWebService getDemoWebServicePort(WebServiceFeature... features) {
        return super.getPort(DemoWebServicePort, IDemoWebService.class, features);
    }

}
