package com.gt.union.webservice.client.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-31T15:26:34.893+08:00
 * Generated source version: 3.1.12
 * 
 */
@WebService(targetNamespace = "http://common.server.webservice.union.gt.com/", name = "IDemoWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface IDemoWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "test1", targetNamespace = "http://common.server.webservice.union.gt.com/", className = "com.gt.union.webservice.client.common.Test1")
    @WebMethod
    @ResponseWrapper(localName = "test1Response", targetNamespace = "http://common.server.webservice.union.gt.com/", className = "com.gt.union.webservice.client.common.Test1Response")
    public java.lang.String test1(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "test2", targetNamespace = "http://common.server.webservice.union.gt.com/", className = "com.gt.union.webservice.client.common.Test2")
    @WebMethod
    @ResponseWrapper(localName = "test2Response", targetNamespace = "http://common.server.webservice.union.gt.com/", className = "com.gt.union.webservice.client.common.Test2Response")
    public com.gt.union.webservice.client.common.ResponseWrapper test2(
        @WebParam(name = "arg0", targetNamespace = "")
        com.gt.union.webservice.client.common.RequestWrapper arg0
    );
}
