
package com.gt.union.webservice.client.common;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-31T15:26:34.864+08:00
 * Generated source version: 3.1.12
 * 
 */
public final class IDemoWebService_DemoWebServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://common.server.webservice.union.gt.com/", "DemoWebServiceImpl");

    private IDemoWebService_DemoWebServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {

        /*URL wsdlURL = DemoWebServiceImpl.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DemoWebServiceImpl ss = new DemoWebServiceImpl(wsdlURL, SERVICE_NAME);
        IDemoWebService port = ss.getDemoWebServicePort();  
        
        {
        System.out.println("Invoking test1...");
        java.lang.String _test1_arg0 = "";
        java.lang.String _test1__return = port.test1(_test1_arg0);
        System.out.println("test1.result=" + _test1__return);


        }
        {
        System.out.println("Invoking test2...");
        com.gt.union.webservice.client.common.RequestWrapper _test2_arg0 = null;
        com.gt.union.webservice.client.common.ResponseWrapper _test2__return = port.test2(_test2_arg0);
        System.out.println("test2.result=" + _test2__return);


        }*/

        DemoWebServiceImpl demoWebService = new DemoWebServiceImpl();
        IDemoWebService iDemoWebService = demoWebService.getDemoWebServicePort();
        String response = iDemoWebService.test1("hello");
        System.out.println("response:" + response);

        RequestWrapper requestWrapper = new RequestWrapper();
        requestWrapper.setName("again");
        ResponseWrapper responseWrapper = iDemoWebService.test2(requestWrapper);
        System.out.println("responseWrapper:" + responseWrapper.getResult());

        System.exit(0);
    }

}
